trigger:
  branches:
    include:
      - master
  paths:
    include:
      - v0.12.24-ocp4-cluster-upi/*

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: Docker@2
    displayName: "Login docker registry"
    inputs:
       command: login
       containerRegistry: quay.io

  - task: Docker@2
    displayName: "Build and push  docker image"
    inputs:
      Dockerfile: "**/v0.12.24/Dockerfile"
      command: buildAndPush
      repository: ci-container-images/terraform
      tags: |
        v0.12.24
    


  - task: Docker@2
    displayName: "Build and push  terraform image for OpenShift UPI provisioning environment"
    inputs:
      Dockerfile: "**/v0.12.24-ocp4-cluster-upi/Dockerfile"
      command: buildAndPush
      repository: ci-container-images/terraform
      tags: |
        v0.12.24-ocp4-cluster-upi

  - task: Docker@2
    displayName: "Build and push  terraform image for gitlab-group module"
    inputs:
      Dockerfile: "**/v0.12.24-gitlab-group-tf-module-deps/Dockerfile"
      command: buildAndPush
      repository: ci-container-images/terraform
      tags: |
        v0.12.24-gitlab-group-tf-module-deps
