trigger:
- master

pool:
  vmImage: 'ubuntu-latest'


variables:
   - group: quay.io

steps:
- script:  "echo $REGISTRY"
  displayName:  Check libarary variables
  

- script:  "sudo docker info"
  displayName:  'Docker Engine Test'


